/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#7ad0ff',
        'on-tertiary': '#003549',
        'on-error': '#690005',
        'primary-fixed': '#d6e3ff',
        'on-primary-fixed': '#0d1c32',
        'secondary-fixed-dim': '#dcb8ff',
        'surface-container-low': '#1b1b1d',
        'on-surface-variant': '#c5c6cd',
        'error-container': '#93000a',
        'secondary-fixed': '#efdbff',
        'on-secondary': '#480081',
        'on-primary-fixed-variant': '#39475f',
        'primary-container': '#0a192f',
        'surface-container': '#1f1f21',
        tertiary: '#7ad0ff',
        'inverse-on-surface': '#303032',
        'surface-container-highest': '#343536',
        'secondary-container': '#7701d0',
        'surface-container-lowest': '#0e0e10',
        'tertiary-fixed': '#c3e8ff',
        'surface-dim': '#131315',
        'on-tertiary-fixed': '#001e2c',
        'primary-fixed-dim': '#b9c7e4',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#dcb7ff',
        'on-secondary-fixed-variant': '#6700b5',
        'surface-tint': '#b9c7e4',
        'on-tertiary-fixed-variant': '#004c69',
        outline: '#8f9097',
        'surface-container-high': '#2a2a2c',
        'inverse-primary': '#515f78',
        'outline-variant': '#44474d',
        'surface-bright': '#39393b',
        'on-surface': '#e4e2e4',
        surface: '#131315',
        'inverse-surface': '#e4e2e4',
        primary: '#b9c7e4',
        'on-tertiary-container': '#008cbc',
        secondary: '#dcb8ff',
        error: '#ffb4ab',
        'on-background': '#e4e2e4',
        'on-primary': '#233148',
        background: '#131315',
        'on-primary-container': '#74829d',
        'surface-variant': '#343536',
        'on-secondary-fixed': '#2c0051',
        'tertiary-container': '#001c29',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max-width': '1440px',
        gutter: '24px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      animation: {
        'float': 'float 4s ease-in-out infinite',
        'pulse-teal': 'pulse-teal 2s infinite',
      },
      keyframes: {
        float: {
          '0%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0px)' },
        },
        'pulse-teal': {
          '0%': { boxShadow: '0 0 0 0 rgba(122, 208, 255, 0.4)' },
          '70%': { boxShadow: '0 0 0 10px rgba(122, 208, 255, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(122, 208, 255, 0)' },
        },
      },
      backgroundImage: {
        'electric-gradient': 'linear-gradient(135deg, #7701d0 0%, #b9c7e4 100%)',
      },
    },
  },
  plugins: [],
};