/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131315',
        'surface-dim': '#131315',
        'surface-bright': '#39393b',
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1b1b1d',
        'surface-container': '#1f1f21',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#343536',
        'on-surface': '#e4e2e4',
        'on-surface-variant': '#c5c6cd',
        'outline': '#8f9097',
        'outline-variant': '#44474d',
        'surface-tint': '#b9c7e4',
        'primary': '#b9c7e4',
        'on-primary': '#233148',
        'primary-container': '#0a192f',
        'on-primary-container': '#74829d',
        'secondary': '#dcb8ff',
        'on-secondary': '#480081',
        'secondary-container': '#7701d0',
        'on-secondary-container': '#dcb7ff',
        'tertiary': '#7ad0ff',
        'on-tertiary': '#003549',
        'tertiary-container': '#001c29',
        'on-tertiary-container': '#008cbc',
        'tertiary-fixed': '#c3e8ff',
        'tertiary-fixed-dim': '#7ad0ff',
        'on-tertiary-fixed': '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        'background': '#131315',
        'on-background': '#e4e2e4',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      fontFamily: {
        'display-lg': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};